FROM cloudfoundry/cflinuxfs2:1.46.0

WORKDIR /var/lib/beachfront

RUN apt-get update && apt-get install -y \
    git-core

RUN git clone https://github.com/venicegeo/bf-tideprediction.git
WORKDIR /var/lib/beachfront/bf-tideprediction

RUN pip install -r requirements.txt
RUN ./scripts/extract-historical-data.sh

CMD ["gunicorn", "-t", "360", "-w", "5", "bftideprediction:app"]
