version: '3'
services:
  javabuild:
    build:
      context: .
      dockerfile: Dockerfile_javabuild
    image: beachfront/javabuild:1.0.0
    volumes:
      - bfjars:/var/lib/beachfront/target
  javaruntime:
    build:
      context: .
      dockerfile: Dockerfile_javaruntime
    image: beachfront/javaruntime:1.0.0
  access:
    image: beachfront/javaruntime:1.0.0
    depends_on:
      - javabuild
      - javaruntime
      - rabbitmq
      - postgis
      - geoserver
    links:
      - rabbitmq
      - postgis
      - geoserver
    expose:
      - "8085"
    volumes:
      - bfjars:/var/lib/beachfront/target
    entrypoint: /var/lib/beachfront/entrypoint.sh
    command: java -jar target/piazza-access-1.0.0.jar
    environment:
      - spring.profiles.active=basic-geoserver-auth
      - vcap.services.pz-postgres.credentials.jdbc_uri=jdbc:postgresql://postgis:5432/piazza
      - vcap.services.pz-postgres.credentials.db_host=postgis
      - vcap.services.pz-rabbitmq.credentials.protocols.amqp.host=rabbitmq
      - vcap.services.pz-geoserver.credentials.boundless_geoserver_url=http://geoserver:8080/geoserver/index.html
      - vcap.services.pz-blobstore.credentials.access_key_id
      - vcap.services.pz-blobstore.credentials.secret_access_key
      - vcap.services.pz-blobstore.credentials.encryption_key
  gateway:
    image: beachfront/javaruntime:1.0.0
    depends_on:
      - javabuild
      - javaruntime
      - rabbitmq
    links:
      - rabbitmq
    expose:
      - "8081"
    volumes:
      - bfjars:/var/lib/beachfront/target
    entrypoint: /var/lib/beachfront/entrypoint.sh
    command: java -jar target/piazza-gateway-1.0.0.jar
    environment:
      - vcap.services.pz-rabbitmq.credentials.protocols.amqp.host=rabbitmq
      - vcap.services.pz-blobstore.credentials.access_key_id
      - vcap.services.pz-blobstore.credentials.secret_access_key
      - vcap.services.pz-blobstore.credentials.encryption_key
  idam:
    image: beachfront/javaruntime:1.0.0
    depends_on:
      - javabuild
      - javaruntime
      - rabbitmq
      - postgis
    links:
      - rabbitmq
      - postgis
    expose:
      - "8080"
    volumes:
      - bfjars:/var/lib/beachfront/target
    entrypoint: /var/lib/beachfront/entrypoint.sh
    command: java -jar target/piazza-idam-1.0.0.jar
    environment:
      - spring.profiles.active=disable-authn
      - vcap.services.pz-postgres.credentials.jdbc_uri=jdbc:postgresql://postgis:5432/piazza
      - vcap.services.pz-postgres.credentials.db_host=postgis
      - vcap.services.pz-rabbitmq.credentials.protocols.amqp.host=rabbitmq
  rabbitmq:
    image: rabbitmq:3.6.6-management
    expose:
      - "5672"
      - "15672"
  postgis:
    image: mdillon/postgis:9.5
    environment:
      - POSTGRES_USER=piazza
      - POSTGRES_PASSWORD=piazza
      - POSTGRES_DB=piazza
    expose:
      - "5432"
  geoserver:
    image: kartoza/geoserver:latest
    depends_on:
      - postgis
    links:
      - postgis
    expose:
      - "8080"
volumes:
  bfjars:
