version: '3'
services:
  javabuild:
    build:
      context: .
      dockerfile: Dockerfile_javabuild
    image: beachfront/javabuild:1.0.0
    volumes:
      - bfjars:/var/lib/beachfront/target
  javaruntime:
    build:
      context: .
      dockerfile: Dockerfile_javaruntime
    image: beachfront/javaruntime:1.0.0
  access:
    image: beachfront/javaruntime:1.0.0
    depends_on:
      - javabuild
      - javaruntime
      - rabbitmq
      - postgis
      - geoserver
    links:
      - rabbitmq
      - postgis
      - geoserver
    expose:
      - "8081"
    volumes:
      - bfjars:/var/lib/beachfront/target
    command: java -jar target/*access*.jar
  gateway:
    image: beachfront/javaruntime:1.0.0
    depends_on:
      - javabuild
      - javaruntime
      - rabbitmq
      - access
    links:
      - rabbitmq
      - access
    expose:
      - "8085"
    volumes:
      - bfjars:/var/lib/beachfront/target
    command: java -jar target/*gateway*.jar
  rabbitmq:
    image: rabbitmq:3.6.6-management
    expose:
      - "5672"
  postgis:
    image: mdillon/postgis:9.5
    environment:
      - POSTGRES_USER=piazza
      - POSTGRES_PASSWORD=piazza
      - POSTGRES_DB=piazza
    expose:
      - "5432"
  geoserver:
    image: kartoza/geoserver:latest
    depends_on:
      - postgis
    links:
      - postgis
    expose:
      - "8080"
volumes:
  bfjars:
