version: '3'
services:
  bfjava:
    build:
      context: .
      dockerfile: Dockerfile_bfjava
    image: beachfront/bfjava:1.0.0
    volumes:
      - maven:/root/.m2/repository
    command: /var/lib/beachfront/docker_javabuild.sh
volumes:
  maven:
