FROM cloudfoundry/cflinuxfs2:1.46.0

WORKDIR /var/lib/beachfront

RUN apt-get update && apt-get install -y \
    maven \
    software-properties-common \
    git-core
RUN add-apt-repository ppa:openjdk-r/ppa
RUN apt-get update && apt-get install -y \
    openjdk-8-jdk
    
COPY ./docker_build.sh /var/lib/beachfront/docker_build.sh
COPY ./maven/settings.xml /etc/maven/settings.xml

CMD ["echo", "This image has no default run command."]