FROM cloudfoundry/cflinuxfs2:1.46.0

WORKDIR /var/lib/beachfront

RUN apt-get update && apt-get install -y \
    maven \
    software-properties-common \
    git-core
RUN add-apt-repository ppa:openjdk-r/ppa
RUN apt-get update && apt-get install -y \
    openjdk-8-jdk

RUN update-java-alternatives --set /usr/lib/jvm/java-1.8.0-openjdk-amd64

COPY ./docker_javabuild.sh /var/lib/beachfront/docker_javabuild.sh
COPY ./maven/settings.xml /etc/maven/settings.xml

RUN /var/lib/beachfront/docker_javabuild.sh

CMD ["echo", "This image has no default run command."]