FROM cloudfoundry/cflinuxfs2:1.46.0

WORKDIR /var/lib/beachfront

RUN apt-get update && apt-get install -y \
    git-core \
    python-pip \
    python-dev \
    golang-go
RUN pip install --upgrade pip

RUN curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh && \
    /bin/bash miniconda.sh -b -p "/home/beachfront/miniconda3" && \
    rm miniconda.sh && \
    echo "y" | conda update -n root --all && \
    conda config --add channels local && \
    conda install -c conda-forge gdal

CMD ["echo", "This image has no default run command."]
