FROM cloudfoundry/cflinuxfs2:1.46.0

WORKDIR /var/lib/beachfront

RUN apt-get update && apt-get install -y \
    git-core

# Installing GO environment
RUN wget https://dl.google.com/go/go1.10.5.linux-amd64.tar.gz
RUN tar -xzvf go1.10.5.linux-amd64.tar.gz -C /usr/lib/

ENV GOROOT=/usr/lib/go
ENV GOPATH=/var/lib/beachfront
ENV PATH="$GOPATH/bin:/usr/lib/go/bin:$PATH"

WORKDIR /var/lib/beachfront/src/github.com/venicegeo
RUN git clone https://github.com/venicegeo/bf-ia-broker
WORKDIR /var/lib/beachfront/src/github.com/venicegeo/bf-ia-broker

RUN go install github.com/venicegeo/bf-ia-broker/cmd/bf-ia-broker

CMD ["bf-ia-broker", "service"]
