FROM cloudfoundry/cflinuxfs2:1.46.0

WORKDIR /var/lib/beachfront

RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:ubuntugis/ppa
RUN apt-get update && apt-get install -y \
    git-core \
    python-pip \
    python-setuptools \
    libmysqlclient-dev \ 
    python-numpy \
    python-dev \
    libgdal-dev \
    python-gdal \
    swig \
    g++ \
    libagg-dev \
    libpotrace-dev \
    golang-go \
    gdal-bin
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools

RUN git clone https://github.com/venicegeo/beachfront-py.git
WORKDIR /var/lib/beachfront/beachfront-py
RUN pip install -r requirements.txt
RUN pip install .

CMD ["echo", "This image has no default run command."]
