FROM cloudfoundry/cflinuxfs2:1.46.0

WORKDIR /var/lib/beachfront

RUN apt-get update && apt-get install -y \
    software-properties-common \
    postgresql-client
RUN add-apt-repository ppa:openjdk-r/ppa
RUN apt-get update && apt-get install -y \
    openjdk-8-jre

COPY ./dockerfile/scripts/wait-for-services.sh /var/lib/beachfront/wait-for-services.sh

CMD ["echo", "This image has no default run command."]