FROM developmentseed/geolambda:1.0.0

RUN \
    yum makecache fast; \
    yum install -y agg-devel;

ENV \
    POTRACE_VERSION=1.15 \
    PKG_CONFIG_PATH=/usr/lib64/pkgconfig

# Install potrace
RUN \
    wget http://potrace.sourceforge.net/download/$POTRACE_VERSION/potrace-$POTRACE_VERSION.tar.gz; \
    tar -xzvf potrace-$POTRACE_VERSION.tar.gz; \
    cd potrace-$POTRACE_VERSION; \
    ./configure --with-libpotrace; \
    make && make install && cd .. && \
    rm -rf potrace-$POTRACE_VERSION*

RUN pip install beachfront==0.2.5
RUN pip install git+https://github.com/venicegeo/bfalg-ndwi@1.1.4

WORKDIR /home/beachfront

CMD ["echo", "This image has no default run command."]
