FROM cloudfoundry/cflinuxfs3

WORKDIR /var/lib/beachfront

RUN apt-get update && apt-get install -y \
    git-core \
    postgresql-client

# Installing GO environment
RUN wget https://dl.google.com/go/go1.10.5.linux-amd64.tar.gz
RUN tar -xzvf go1.10.5.linux-amd64.tar.gz -C /usr/lib/

ENV GOROOT=/usr/lib/go
ENV GOPATH=/var/lib/beachfront
ENV PATH="$GOPATH/bin:/usr/lib/go/bin:$PATH"

WORKDIR /var/lib/beachfront/src/github.com/venicegeo
RUN git clone https://github.com/venicegeo/bf-ia-broker
WORKDIR /var/lib/beachfront/src/github.com/venicegeo/bf-ia-broker

RUN go install github.com/venicegeo/bf-ia-broker/cmd/bf-ia-broker

COPY ./dockerfile/scripts/wait-for-postgis.sh /var/lib/beachfront/wait-for-postgis.sh

ENTRYPOINT ["/var/lib/beachfront/wait-for-postgis.sh"]

CMD ["sh", "-c", "bf-ia-broker --version; bf-ia-broker migrate; bf-ia-broker serve"]
